###I###R###D######U###2###3###3#######T###R###A###N###S###V###I###H###M###I####
###                                                                         ###
###    /\  ______      ___ ____ _  _ __   ____ __   ____     ______  /\     ###
###    ||  \ \ \ \    / __( ___( \/ )__\ (  _ (  ) (_  _)   / / / /  ||     ###
###    ||   > > > >  ( (_-.)__) \  /(__)\ )   /)(__ _)(_   < < < <   ||     ###
###    ||  /_/_/_/    \___(____) \(__)(__(_)\_(____(____)   \_\_\_\  ||     ###
###    \/                                                            \/     ###
###                                                                         ###
###I###R###D######U###2###3###3#######T###R###A###N###S###V###I###H###M###I####
# Name ___________________ gevarli.smk
# Version ________________ v.2025.04
# Author _________________ Nicolas Fernandez
# Affiliation ____________ IRD_U233_TransVIHMI
# Aim ____________________ Snakefile running GeVarLi rules
# Date ___________________ 2021.10.12
# Latest modifications ___ 2025.04.04
# Use ____________________ snakemake -s Snakefile --use-conda
###############################################################################

###############################################################################
### CONFIGURATION ###
#####################

# Config file
configfile: "config/config.yaml"

###############################################################################
### FUNCTIONS ###
#################

# Imports
import time, re

from snakemake.utils import min_version
from snakemake.utils import validate

from scripts.functions import get_valid_fastq
from scripts.functions import get_settings
from scripts.functions import get_bam_input
from scripts.functions import get_bai_input
from scripts.functions import get_final_outputs
from scripts.functions import get_time

# Local
FASTQ_DIR = config["fastq_dir"]
VALID_FASTQ, SAMPLE_WARNINGS = get_valid_fastq(FASTQ_DIR)
SAMPLE = list(VALID_FASTQ.keys())
MATE = ["1", "2"]
QC_REF, = glob_wildcards("resources/genomes/fastq-screen/{qc_ref}.fasta")
START_TIME = time.time()

# Exports
import scripts.functions as functions
functions.FASTQ_DIR = FASTQ_DIR
functions.SAMPLE_WARNINGS = SAMPLE_WARNINGS
functions.SAMPLE = SAMPLE
functions.MATE = MATE
functions.QC_REF = QC_REF
functions.START_TIME = START_TIME
functions.MODULES = config["modules"] # Modules
functions.MAPPER = config["tools"]["mapper"]     # Reads mapper ('bwa', 'minimap2' or 'bowtie2')
functions.CALLER = config["tools"]["caller"]     # Variants caller ('ivar' or 'ivar')
functions.ASSIGNER = config["tools"]["assigner"] # Lineages assigner ('nextclade' or 'pangolin')
functions.REFERENCE = config["consensus"]["reference"] # Genome reference sequence, in fasta format
functions.MIN_DEPTH = config["consensus"]["min_depth"] # Minimum depth to call consensus, mark lower regions with 'N'
functions.STAT_EXT = config["report"]["stat"]["extention"] # Stat reports extentions ('txt' 'tsv' 'json')

# Snakemake version
min_version("9.1.7")

# Schemas
validate(config, schema="schemas/config.schema.yaml")

###############################################################################
### WILDCARDS ###
#################

wildcard_constraints:
    reference = "^[A-Z]{1,2}[0-9]{5,7}$",
    mapper = "^(?:bwa|minimap2|bowtie2)$",
    caller = "^(?:ivar)$",
    assigner = "^(?:nextclade|pangolin)$"

###############################################################################
### RESOURCES ###
#################

CPUS = config["resources"]["cpus"]       # Threads (maximum)
RAM = config["resources"]["ram"]         # Memory (RAM) in Gb (maximum)
TMP_DIR = config["resources"]["tmp_dir"] # Temporary directory

###############################################################################
### ENVIRONMENTS ###
####################

FASTQ_SCREEN = config["envs"]["fastq_screen"] # Fastq-Screen conda environment
FASTQC= config["envs"]["fastqc"]              # FastQC conda environment
CUTADAPT = config["envs"]["cutadapt"]         # Cutadapt conda environment
SICKLE_TRIM = config["envs"]["sickle_trim"]   # Sickle-Trim conda environment
MINIMAP2 = config["envs"]["minimap2"]         # BWA conda environment
BWA = config["envs"]["bwa"]                   # BWA conda environment
BOWTIE2 = config["envs"]["bowtie2"]           # Bowtie2 conda environment
SAMTOOLS = config["envs"]["samtools"]         # SamTools conda environment
BEDTOOLS = config["envs"]["bedtools"]         # BedTools conda environment
GAWK = config["envs"]["gawk"]                 # Awk (GNU) conda environment
IVAR = config["envs"]["ivar"]                 # iVar conda environment
TSV2VCF = config["envs"]["tsv2vcf"]           # tsv2vcf conda environment
BCFTOOLS = config["envs"]["bcftools"]         # BcfTools conda environment
PANGOLIN = config["envs"]["pangolin"]         # Pangolin conda environment
NEXTCLADE = config["envs"]["nextclade"]       # Nextclade conda environment
MULTIQC = config["envs"]["multiqc"]           # Multi-QC conda environment
WORKFLOW = config["envs"]["workflow"]         # Workflow conda environment

###############################################################################
### PARAMETERS ###
##################

MAPPER = config["tools"]["mapper"]       # Mapper ('bwa', 'minimap2' or 'bowtie2')
CALLER = config["tools"]["caller"]       # Variant Caller ('ivar' or 'ivar')
ASSIGNER = config["tools"]["assigner"]   # Lineage assigner ('nextclade' or 'pangolin')

REFERENCE = config["consensus"]["reference"] # Genome reference sequence, in fasta format
MIN_DEPTH = config["consensus"]["min_depth"] # minimum depth
MAX_DEPTH = config["consensus"]["max_depth"] # maximum depth
MIN_FREQ = config["consensus"]["min_freq"]   # minimum allele frequency
MIN_INDEL = config["consensus"]["min_indel"] # minimum indel frequency
MIN_BQ = config["consensus"]["min_bq"]       # minimum base quality
MIN_QUAL = config["consensus"]["min_qual"]   # minimum mapping quality
MAP_QUAL = config["consensus"]["map_qual"]   # minimum mapping quality

FQC_SUBSET = config["fastq_screen"]["subset"] # Fastq-Screen --subset
FQC_CONFIG = config["fastq_screen"]["config"] # Fastq-Screen --conf
#MQC_PATH = config["multiqc"]["path"]          # MultiQC --conf
#MQC_CONF = config["multiqc"]["config"]        # MultiQC --conf
#TAG = config["multiqc"]["tag"]                # MultiQC --tag

CUT_CLIPPING = config["cutadapt"]["clipping"]       # Cutadapt --cut
CUT_LENGTH = config["cutadapt"]["length"]           # Cutadapt --minimum-length
CUT_ADAPTERS = config["cutadapt"]["adapters"]       # Cutadapt --adapter

SIC_COMMAND = config["sickle_trim"]["command"]   # Sickle-trim command
SIC_ENCODING = config["sickle_trim"]["encoding"] # Sickle-trim --qual-type 
SIC_QUALITY = config["sickle_trim"]["quality"]   # Sickle-trim --qual-threshold
SIC_LENGTH = config["sickle_trim"]["length"]     # Sickle-trim --length-treshold

BWA_ALGO = config["bwa"]["algorithm"] # BWA indexing algorithm

MM2_KMER_SIZE = config["minimap2"]["algorithm"]["k-mer_size"]          # MM2 k-mer size
MM2_MINIMIZER_SIZE = config["minimap2"]["algorithm"]["minimizer_size"] # MM2 minimizer window size
MM2_SPLIT_SIZE = config["minimap2"]["algorithm"]["split_size"]         # MM2 split index
MM2_PRESET = config["minimap2"]["preset"] # Minimap2 presetv           # MM2 preset
#MM2_LENGTH = config["minimap2"]["length"]                              # Minimap2 length
#MM2_HOMOPOLYMER = config["minimap2"]["algorithm"]["homopolymer"]       # MM2 homopolymer if PacBio

BT2_ALGO = config["bowtie2"]["algorithm"]          # Bowtie2 indexing algorithm
BT2_SENSITIVITY = config["bowtie2"]["sensitivity"] # Bowtie2 sensitivity preset

PRIMER_BED_PATH = config["primers"]["bed"]["path"]     # primer kit bed path
PRIMER_BED_SCHEME = config["primers"]["bed"]["scheme"] # primer kit bed scheme
PRIMER_OFFSET = config["primers"]["offset"]            # offset
PRIMER_MIN_LENGTH = config["primers"]["min_length"]    # minimum length
PRIMER_MIN_QUAL = config["primers"]["min_qual"]        # minimum quality
PRIMER_SLIDE = config["primers"]["slide"]              # slide windows

NEXT_PATH = config["nextclade"]["path"]       # Path to nextclade dataset
NEXT_DATASET = config["nextclade"]["dataset"] # Nextclade dataset

GRAPH_TYPE = config["report"]["graph"]["type"]     # Graph type
GRAPH_EXT = config["report"]["graph"]["extention"] # Graph extention

###############################################################################
### LOAD RULES ###
##################

include: "rules/samples_prep.smk"
include: "rules/quality_controls.smk"
include: "rules/reads_cleanning.smk"
include: "rules/genomes_indexing.smk"
include: "rules/reads_mapping.smk"
include: "rules/primers_clipping.smk"
include: "rules/duplicates_removing.smk"
include: "rules/coverage_stats.smk"
include: "rules/lowcov_masking.smk"
include: "rules/variants_calling.smk"
include: "rules/consensus_calling.smk"
include: "rules/lineages_calling.smk"
include: "rules/gisaid_submission.smk"
include: "rules/results_merging.smk"
include: "rules/workflow_reporting.smk"

###############################################################################
### DEBUG ###
#############



###############################################################################
### TARGET RULES ###
####################

rule all:
    input:
        html_report = "results/10_Reports/workflow-report.html"

###############################################################################
### HOOKS ###
#############

onstart:
    print("\n \033[94m ===> GeVarLi Workflow : Start! <=== \033[0m \n")
    get_settings(config, START_TIME)
    print("\n")

onsuccess:
    print("\n \033[92m ===> GeVarLi Workflow : Success! <=== \033[0m \n")
    get_time(START_TIME)
    shell("mkdir -p results/10_Reports/envs/ 2> /dev/null")
    shell("cp workflow/envs/*.yaml results/10_Reports/envs/ 2> /dev/null")
    shell("cp config/config.yaml results/10_Reports/config.log 2> /dev/null")
    shell("tar -czf results/Reports_archive.tar.gz -C results/ 10_Reports/")
    print("\n")

onerror:
    print("\n \033[91m ===> GeVarLi Workflow : Error... <=== \033[0m \n")
    get_time(START_TIME)
    shell("mkdir -p results/10_Reports/envs/ 2> /dev/null")
    shell("cp workflow/envs/*.yaml results/10_Reports/envs/ 2> /dev/null")
    shell("cp config/config.yaml results/10_Reports/config.log 2> /dev/null")
    shell("tar -czf results/Reports_archive.tar.gz -C results/ 10_Reports/")
    print("\n")

###############################################################################
###############################################################################