###I###R###D######U###2###3###3#######T###R###A###N###S###V###I###H###M###I####
###                                                                         ###
###    /\  ______      ___ ____ _  _ __   ____ __   ____     ______  /\     ###
###    ||  \ \ \ \    / __( ___( \/ )__\ (  _ (  ) (_  _)   / / / /  ||     ###
###    ||   > > > >  ( (_-.)__) \  /(__)\ )   /)(__ _)(_   < < < <   ||     ###
###    ||  /_/_/_/    \___(____) \(__)(__(_)\_(____(____)   \_\_\_\  ||     ###
###    \/                                                            \/     ###
###                                                                         ###
###I###R###D######U###2###3###3#######T###R###A###N###S###V###I###H###M###I####
# Name ___________________ gevarli.smk
# Version ________________ v.2025.01
# Author _________________ Nicolas Fernandez
# Affiliation ____________ IRD_U233_TransVIHMI
# Aim ____________________ Snakefile running GeVarLi rules
# Date ___________________ 2021.10.12
# Latest modifications ___ 2025.03.12
# Use ____________________ snakemake -s Snakefile --use-conda -j
###############################################################################

###############################################################################
### CONFIGURATION ###
#####################

configfile: "config/config.yaml"

###############################################################################
### FUNCTIONS ###
#################

# Imports
from snakemake.utils import min_version
from snakemake.utils import validate

from scripts.functions import get_valid_fastq
from scripts.functions import get_final_outputs
from scripts.functions import get_bam_input
from scripts.functions import get_bai_input

# Local
FASTQ_DIR = config["fastq_dir"]
VALID_FASTQ = get_valid_fastq(FASTQ_DIR)
SAMPLE = list(VALID_FASTQ.keys())
MATE = ["1", "2"]

# Exports
import scripts.functions as functions
functions.SAMPLE = SAMPLE
functions.MATE = MATE
functions.MODULES = config["modules"] # Modules
functions.REFERENCE = config["consensus"]["reference"]   # Genome reference sequence, in fasta format
functions.QC_REF = config["fastq_screen"]["reference"]   # FastqScreen config file genomes to index
functions.MAPPER = config["consensus"]["mapper"]       # Mapper ('bwa' 'minimap2' 'bowtie2')
functions.MIN_COV = config["consensus"]["min_cov"]       # Minimum coverage, mask lower regions with 'N'
functions.CALLER = config["consensus"]["caller"]         # Variants caller ('ivar')
functions.ASSIGNER = config["consensus"]["assigner"] # Tools ('nextclade' 'pangolin')

functions.STAT_EXT = config["report"]["stat"]["extention"] # Stat reports extentions ('txt' 'tsv' 'json')

# Snakemake version
min_version("8.27.0")

# Schemas
#validate(config, schema="schemas/config.schema.yaml")

###############################################################################
### WILDCARDS ###
#################

#FASTQ, = glob_wildcards("resources/symlinks/{fastq}.fastq.gz")
#SAMPLE, = glob_wildcards("resources/symlinks/{sample}_R1.fastq.gz")

###############################################################################
### RESOURCES ###
#################

CPUS = config["resources"]["cpus"]       # Threads (maximum)
RAM = config["resources"]["ram"]         # Memory (RAM) in Gb (maximum)
TMP_DIR = config["resources"]["tmp_dir"] # Temporary directory

###############################################################################
### ENVIRONMENTS ###
####################

MULTIQC = config["envs"]["multiqc"]           # Multi-QC conda env
FASTQ_SCREEN = config["envs"]["fastq_screen"] # Fastq-Screen conda env
FASTQC= config["envs"]["fastqc"]              # FastQC conda env
CUTADAPT = config["envs"]["cutadapt"]         # Cutadapt conda environment
SICKLE_TRIM = config["envs"]["sickle_trim"]   # Sickle-Trim conda environment
MINIMAP2 = config["envs"]["minimap2"]         # BWA conda environment
BWA = config["envs"]["bwa"]                   # BWA conda environment
BOWTIE2 = config["envs"]["bowtie2"]           # Bowtie2 conda environment
SAMTOOLS = config["envs"]["samtools"]         # SamTools conda environment
BEDTOOLS = config["envs"]["bedtools"]         # BedTools conda environment
BAMCLIPPER = config["envs"]["bamclipper"]     # BAMClipper
GAWK = config["envs"]["gawk"]                 # Awk (GNU) conda environment
IVAR = config["envs"]["ivar"]                 # iVar conda environment
TSV2VCF = config["envs"]["tsv2vcf"]           # tsv2vcf conda environment
BCFTOOLS = config["envs"]["bcftools"]         # BcfTools conda environment
PANGOLIN = config["envs"]["pangolin"]         # Pangolin conda environment
NEXTCLADE = config["envs"]["nextclade"]       # Nextclade conda environment
WORKFLOW = config["envs"]["workflow"]         # Workflow conda environment  

###############################################################################
### PARAMETERS ###
##################

SUBSET = config["fastq_screen"]["subset"]     # Fastq-Screen --subset
FQC_CONFIG = config["fastq_screen"]["config"] # Fastq-Screen --conf
#MQC_PATH = config["multiqc"]["path"]          # MultiQC --conf
#MQC_CONF = config["multiqc"]["config"]        # MultiQC --conf
#TAG = config["multiqc"]["tag"]                # MultiQC --tag

KMER_SIZE = config["minimap2"]["algorithm"]["k-mer_size"]          # MM2 k-mer size
MINIMIZER_SIZE = config["minimap2"]["algorithm"]["minimizer_size"] # MM2 minimizer window size
SPLIT_SIZE = config["minimap2"]["algorithm"]["split_size"]         # MM2 split index
#HOMOPOLYMER = config["minimap2"]["algorithm"]["homopolymer"]       # MM2 if PacBio

BWA_ALGO = config["bwa"]["algorithm"]     # BWA indexing algorithm
BT2_ALGO = config["bowtie2"]["algorithm"] # BT2 indexing algorithm

#REFERENCE = config["consensus"]["reference"] # Genome reference sequence, in fasta format
MIN_COV = config["consensus"]["min_cov"]     # Minimum coverage, mask lower regions with 'N'
IUPAC = config["consensus"]["iupac"]         # Output variants in the form of IUPAC ambiguity codes
MAPPER = config["consensus"]["mapper"]     # Mapper ('minimap2', 'bwa' or 'bowtie2')
CALLER = config["consensus"]["caller"]       # Variant Caller ('lofreq' or 'ivar')
ASSIGNER = config["consensus"]["assigner"]   # Lineage assigner ('nextclade' or 'pangolin')

CUT_LENGTH = config["cutadapt"]["length"]           # Cutadapt --minimum-length
CUT_TRUSEQ = config["cutadapt"]["kits"]["truseq"]   # Cutadapt --adapter Illumina TruSeq
CUT_NEXTERA = config["cutadapt"]["kits"]["nextera"] # Cutadapt --adapter Illumina Nextera
CUT_SMALL = config["cutadapt"]["kits"]["small"]     # Cutadapt --adapter Illumina Small
CUT_CLIPPING = config["cutadapt"]["clipping"]       # Cutadapt --cut

SIC_COMMAND = config["sickle_trim"]["command"]   # Sickle-trim command
SIC_ENCODING = config["sickle_trim"]["encoding"] # Sickle-trim --qual-type 
SIC_QUALITY = config["sickle_trim"]["quality"]   # Sickle-trim --qual-threshold
SIC_LENGTH = config["sickle_trim"]["length"]     # Sickle-trim --length-treshold

MM2_PRESET = config["minimap2"]["preset"] # Minimap2 preset
#MM2_LENGTH = config["minimap2"]["length"]                              # Minimap2 length
#MM2_KMER_SIZE = config["minimap2"]["algorithm"]["k-mer_size"]          # Minimap2 k-mer size
#MM2_MINIMIZER_SIZE = config["minimap2"]["algorithm"]["minimizer_size"] # Minimap2 minimizer window size  
#MM2_SPLIT_SIZE = config["minimap2"]["algorithm"]["split_size"]         # Minimap2 split index
#MM2_HOMOPOLYMER = config["minimap2"]["algorithm"]["homopolymer"]       # Minimap2 for PacBio

BWA_ALGO = config["bwa"]["algorithm"] # BWA indexing algorithm

BT2_ALGO = config["bowtie2"]["algorithm"]          # Bowtie2 indexing algorithm
BT2_SENSITIVITY = config["bowtie2"]["sensitivity"] # Bowtie2 sensitivity preset

CLIPPATH = config["bamclipper"]["path"]         # Bamclipper path to primers
PRIMERS = config["bamclipper"]["primers"]       # Bamclipper primers bed files
UPSTREAM = config["bamclipper"]["upstream"]     # Bamclipper upstream nucleotides
DOWNSTREAM = config["bamclipper"]["downstream"] # Bamclipper downstream nucleotides

IVAR_MIN_DEPTH = config["consensus"]["min_cov"]   # iVar
IVAR_MIN_FREQ = config["consensus"]["min_freq"]   # iVar minimum allele frequency allowed 
IVAR_MIN_INSERT = config["consensus"]["min_freq"] # iVar minimum insertion frequency allowed
#IVAR_MIN_DEPTH = config["ivar"]["min_depth"]      # iVar
#IVAR_MIN_FREQ = config["ivar"]["min_freq"]        # iVar minimum allele frequency allowed 
#IVAR_MIN_INSERT = config["ivar"]["min_insert"]    # iVar minimum insertion frequency allowed
IVAR_MAX_DEPTH = config["ivar"]["max_depth"]      # iVar 
IVAR_MIN_BQ = config["ivar"]["min_bq"]            # iVar
IVAR_MIN_QUAL = config["ivar"]["min_qual"]        # iVar
IVAR_MAP_QUAL = config["ivar"]["map_qual"]        # iVar mapping quality

NEXT_PATH = config["nextclade"]["path"]       # Path to nextclade dataset
NEXT_DATASET = config["nextclade"]["dataset"] # Nextclade dataset

GRAPH_TYPE = config["report"]["graph"]["type"]
GRAPH_EXT = config["report"]["graph"]["extention"]

###############################################################################
### LOAD RULES ###
##################

include: "rules/symlinks_renamming.smk"
include: "rules/quality_controls.smk"
include: "rules/reads_cleanning.smk"
include: "rules/genomes_indexing.smk"
include: "rules/reads_mapping.smk"
include: "rules/primers_clipping.smk"
include: "rules/duplicates_removing.smk"
include: "rules/coverage_stats.smk"
include: "rules/lowcov_masking.smk"
include: "rules/variants_calling.smk"
include: "rules/consensus_calling.smk"
include: "rules/lineages_calling.smk"
include: "rules/gisaid_submission.smk"
include: "rules/results_merging.smk"
include: "rules/workflow_reporting.smk"

###############################################################################
### TARGET RULES ###
####################

rule all:
    input:
        report = "results/10_Reports/snakemake/workflow-report.html"

###############################################################################
