---
###I###R###D######U###2###3###3#######T###R###A###N###S###V###I###H###M###I####
# Name ___________________ config.yaml
# Version ________________ v.2022.11
# Author _________________ Nicolas Fernandez
# Affiliation ____________ IRD_U233_TransVIHMI
# Aim ____________________ Configuration yaml file for gevarli.smk snakefile
# Date ___________________ 2021.10.12
# Latest modifications ___ 2022.11.14
# Use ____________________ Edit default settings

###############################################################################

### RESOURCES ----------------------------------------------------------------------------------------
resources:
  cpus: 12           # Set maximum cpus usage (for multithreading, default: 8) [INT]
  ram: 54           # Set maximum memory usage (in Gb, default: 16) [INT]
  tmpdir: '$TMPDIR' # Temporary directory (default: '$TMPDIR')
  ## Examples:
    ## '$TMPDIR'  # System variable $TMPDIR (dafault)
    ## '.'        # Local (i.e. GeVarLi root directory)
    ## '/scratch' # HPC (set it to match your HPC usage)

#snakemake_version: '7.18.1' # Snakemake version (upgrade from  6.12.3)
conda_frontend: 'mamba'     # Conda frontend (conda or mamba)

### ENVIRONNEMENTS -----------------------------------------------------------------------------------
conda:
  osx:                                                     # Conda OSX environement yaml files:
    bamclipper:   '../envs/osx/bamclipper_v.1.0.yaml'        # BAMClipper   ver. 1.0
    bcftools:     '../envs/osx/bcftools_v.1.15.1.yaml'       # Bcftools     ver. 1.15.1
    bedtools:     '../envs/osx/bedtools_v.2.30.0.yaml'       # Bedtools     ver. 2.30.0
    bowtie2:      '../envs/osx/bowtie2_v.2.4.5.yaml'         # Bowtie2      ver. 2.4.5
    bwa:          '../envs/osx/bwa_v.0.7.17.yaml'            # BWA          ver. 0.7.17
    cutadapt:     '../envs/osx/cutadapt_v.4.1.yaml'          # Cutadapt     ver. 4.1
    fastq-screen: '../envs/osx/fastq-screen_v.0.15.2.yaml'   # Fastq-Screen ver. 0.15.2
    fastqc:       '../envs/osx/fastqc_v.0.11.9.yaml'         # FastQC       ver. 0.11.9
    gawk:         '../envs/osx/gawk_v.5.1.0.yaml'            # Awk          ver. 5.1.0
    gevarli-base: '../envs/osx/gavarli-vase_v.2022.11'       # GeVarLi-Base ver. 2022.11
    lofreq:       '../envs/osx/lofreq_v.2.1.5.yaml'          # Lofreq       ver. 2.1.5
    multiqc:      '../envs/osx/multiqc_v.1.12.yaml'          # MultiQC      ver. 1.12
    nextclade:    '../envs/osx/nextclade_v.2.8.0.yaml'       # Nextclade    ver. 2.5.0
    pangolin:     '../envs/osx/pangolin_v.4.0.6.yaml'        # Pangolin     ver. 4.0.6
    samtools:     '../envs/osx/samtools_v.1.15.1.yaml'       # Samtools     ver. 1.15.1
    sickle-trim:  '../envs/osx/sickle-trim_v.1.33.yaml'      # Sickle-trim  ver. 1.33
  linux:                                                   # Conda Linux environement yaml files:
    bamclipper:   '../envs/linux/bamclipper_v.1.0.yaml'      # BAMClipper   ver. 1.0
    bcftools:     '../envs/linux/bcftools_v.1.15.1.yaml'     # Bcftools     ver. 1.15.1
    bedtools:     '../envs/linux/bedtools_v.2.30.0.yaml'     # Bedtools     ver. 2.30.0
    bowtie2:      '../envs/linux/bowtie2_v.2.4.5.yaml'       # Bowtie2      ver. 2.4.5
    bwa:          '../envs/linux/bwa_v.0.7.17.yaml'          # BWA          ver. 0.7.17
    cutadapt:     '../envs/linux/cutadapt_v.4.1.yaml'        # Cutadapt     ver. 4.1
    fastq-screen: '../envs/linux/fastq-screen_v.0.15.2.yaml' # Fastq-Screen ver. 0.15.2
    fastqc:       '../envs/linux/fastqc_v.0.11.9.yaml'       # FastQC       ver. 0.11.9
    gawk:         '../envs/linux/gawk_v.5.1.0.yaml'          # Awk          ver. 5.1.0
    gevarli-base: '../envs/linux/gavarli-vase_v.2022.11'     # GeVarLi-Base ver. 2022.11
    lofreq:       '../envs/linux/lofreq_v.2.1.5.yaml'        # Lofreq       ver. 2.1.5
    multiqc:      '../envs/linux/multiqc_v.1.12.yaml'        # MultiQC      ver. 1.12
    nextclade:    '../envs/linux/nextclade_v.2.8.0.yaml'     # Nextclade    ver. 2.5.0
    pangolin:     '../envs/linux/pangolin_v.4.0.6.yaml'      # Pangolin     ver. 4.0.6
    samtools:     '../envs/linux/samtools_v.1.15.1.yaml'     # Samtools     ver. 1.15.1
    sickle-trim:  '../envs/linux/sickle-trim_v.1.33.yaml'    # Sickle-trim  ver. 1.33

### GISAID (soon) ------------------------------------------------------------------------------------
gisaid:
  username: 'username'
  threshold: '30'
  name: 'hCoV-19'
  country: 'France'
  identifier: ''
  year: '2022'

### CONSENSUS ----------------------------------------------------------------------------------------
consensus:
  path: 'resources/genomes/' # Path to genomes references
  reference: 'Swinepox-virus_India_MW036632-1' # Your reference, in fasta format
  # Available options:
    #- 'SARS-CoV-2_Wuhan_MN908947-3'      # SARS-CoV-2 (default)
    #- 'Monkeypox-virus_Zaire_AF380138-1' # Monkeypox  (without BamClipper and Pangolin)
    #- 'Monkeypox-virus_UK_MT903345-1'    # Monkeypox  (without Pangolin)
    #- 'Swinepox-virus_India_MW036632-1'  # Swinepox   (without BamClipper and Pangolin)
    #- 'Ebola-virus_Zaire_AF272001-1'     # Ebola      (without Nextclade and Pangolin)
    #- 'Nipah-virus_Malaysia_AJ564622-1'  # Nipah      (without Nextclade and Pangolin)
    #- 'HIV-1_HXB2_K03455-1'              # HIV-1      (without BamClipper, Nextclade and Pangolin)
    #- 'Add_your_favorite_genome_ref'     # Custom     (without BamClipper, Nextclade and Pangolin)
  mincov: 30 # Minimum coverage, mask lower regions with 'N' (default: '30') [INT]
  minaf: 0.2 # Minimum allele frequency allowed (default: '0.2') [FLOAT]
  iupac: ''  # Output variants in the form of IUPAC ambiguity codes (default: deactivate)
  # Available options:
    #- ''        # Deactivate (default)
    #- '--iupac' # Activate

### ALIGNER ------------------------------------------------------------------------------------------
aligner: 'bwa' # Select your favorite aligner
# Available options:
  #- 'bwa'     # Faster (default)
  #- 'bowtie2' # Slower, 'sensitivity' requiried and should be set (see below "Bowtie2" options)

### BWA ----------------------------------------------------------------------------------------------
bwa:
  path: 'resources/indexes/bwa/' # Path to BWA indexes
  algorithm: '' # Algorithm for constructing BWA index (default: auto)
  # Available options:
    #- ''         # Auto-select (default)
    #- '-a is'    # Moderately fast, but does not work with database larger than 2GB
    #- '-a bwtsw' # This method works with the whole human genome

### BOWTIE2 ------------------------------------------------------------------------------------------
bowtie2:
  path: 'resources/indexes/bowtie2/' # Path to Bowtie2 indexes
  sensitivity: '--very-sensitive'    # Bowtie2 sensitivity preset (default: '--very-sensitive')
  # Available options:
    #- '--very-fast'      # Same as options: -D 5 -R 1 -N 0 -L 22 -i S,0,2.50
    #- '--fast'           # Same as options: -D 10 -R 2 -N 0 -L 22 -i S,0,2.50
    #- '--sensitive'      # Same as options: -D 15 -R 2 -N 0 -L 22 -i S,1,1.15
    #- '--very-sensitive' # Same as options: -D 20 -R 3 -N 0 -L 20 -i S,1,0.50 (default)
  algorithm: '' # Algorithm for constructing BT2 index
  # Available options:
    #- ''              # (default)
    #- '--large-index' # Force generated index to be 'large', even if reference has fewer than 4 billion nucleotides

### BAMCLIPPER ---------------------------------------------------------------------------------------
bamclipper:
  clipping: 'no' # Do you need to clip amplicon primers ? Need to provide primers bedpe file (or bed)
  # Available options:
    #- 'no'  # Deactivate (default)
    #- 'yes' # Activate
  path: 'resources/primers/bedpe/' # Path to primers bedpe files
  primers: 'SARS-CoV-2_Wuhan_MN908947-3_artic-primers-V3'
  # Reference sequence names and coordinates of BAM and BED are assumed to be derived from identical reference sequences
  # Available options:
    #- 'SARS-CoV-2_Wuhan_MN908947-3_artic-primers-V1'           # SARS-CoV-2 Artic V1
    #- 'SARS-CoV-2_Wuhan_MN908947-3_artic-primers-V2'           # SARS-CoV-2 Artic V2
    #- 'SARS-CoV-2_Wuhan_MN908947-3_artic-primers-V3'           # SARS-CoV-2 Artic V3
    #- 'SARS-CoV-2_Wuhan_MN908947-3_artic-primers-V4'           # SARS-CoV-2 Artic V4 (not based on V3, see Artic README)
    #- 'SARS-CoV-2_Wuhan_MN908947-3_arctiv-primers-V4-1'        # SARS-CoV-2 Artic V4.1 (update to the V4, see Artic README)
    #- 'Ebola-virus_Zaire_KR063671-1_artic-primers-V1'          # EBOV Artic V1
    #- 'Ebola-virus_Zaire_AF272001-1_artic-primers-V2'          # EBOV Artic V2 (based on AF272001.1)
    #- 'Ebola-virus_Zaire_KR063671-1_artic-primers-V3'          # EBOV Artic V3
    #- 'Nipah-virus_Malaysia_AJ564622-1_artic-primers-V1'       # NIV Artic V1
    #- 'Monkeypox-virus_UK_MT903345-1_custom-VGCARE-primers-V1' # MPXV VGCARE V1
    #- 'Add_your_favorite_amplicon_kit'                         # Custom
  upstream: '1'   # (default: 1)
  downstream: '5' # (default: 5)

### SICKLE-TRIM --------------------------------------------------------------------------------------
sickle-trim:
  command: 'pe'      # Reading (default and should be 'pe' for paired-end sequences)
  encoding: 'sanger' # Quality encoding (dafault, and should be 'sanger')
  # Available options (only for information):
    #- 'sanger'   # CASAVA >= 1.8 for "recent" Illumina reads (default)
    #- 'illumina' # CASAVA 1.3 to 1.7 for "old" Illumina reads
    #- 'solexa'   # CASAVA < 1.3 for Solexa
  quality: '30'      # Phred score limit (default: '30')
  length: '50'       # Read length limit after trim (default: '50')

### CUTADAPT -----------------------------------------------------------------------------------------
cutadapt:
  length: '50' # Discard reads shorter than 'length' after trim (default: '50')
  kits:        # Sequence of an adapter ligated to the 3' end of the first read
    truseq:  'AGATCGGAAGAGC'         # Illumina "TruSeq" or "ScriptSeq" based libraries kits
    nextera: 'CTGTCTCTTATACACATC'    # Illumina "Nextera" or "TruSight" based libraries kits
    small:   'TGGAATTCTCGGGTGCCAAGG' # Illumina "Small" based libraries kits

### FASTQSCREEN --------------------------------------------------------------------------------------
fastq-screen:
  config: 'config/fastq-screen.conf' # Path to the fastq-screen configuration file
  subset: 1000                       # Don't use whole sequences, but a subset reads (default: '1000') [INT] (0='all')
  mapper: 'bwa'                      # Mapper used by fastq-screen for alignments (default and should be 'bwa')
  # Available options:
    #- 'bwa'     # Burrows-Wheeler Aligner (default, somme small genomes indexes provided, see 'fastq-screen.conf')
    #- 'bowtie'  # Bowtie (indexes not provided for fastq-screen)
    #- 'bowtie2' # Bowtie2 (indexes not provided for fastq-screen)

### NEXTCLADE ----------------------------------------------------------------------------------------
nextclade:
  path: 'resources/nextclade/' # Path to nextclade datasets
  #dataset: 'sars-cov-2' # Nextclade dataset (depreciated)
  # Available options:
    #- 'sars-cov-2' # SARS-CoV-2 (now default with SARS-CoV-2_Wuhan-WIV04_2019)
    #- 'MPXV'       # Monkeypox all clades (now default with Monkeypox-virus_Zaire)
    #- 'hMPXV'      # human Monkeypox
    #- 'hMPXV_B1'   # human Monkeypox Lineage B1*

### OPERATING-SYSTEM ---------------------------------------------------------------------------------
os: 'osx' # Operating System (default: OSX)
# Available options:
  #- 'osx'     # Mac OSX - Apple (R) [UNIX] (suported)
  #- 'linux'   # GNU Linux - Free [UNIX] (suported)
  #- 'bsd'     # Free BSD - Free [UNIX] (not tested. Need specific conda env. ?)
  #- 'solaris' # Oracle Solaris - Sun Microsystems (R) [UNIX] (not tested. Need specific conda env. ?)
  #- 'windows' # Windows - Microsoft Corporation (R) (not suported, not [UNIX])
