---
###############################################################################
# Author: Nicolas Fernandez
# Affiliation: IRD_TransVIHMI
# Aim: Configuration file for gevarli.smk snakefile
# Date: 2021.10.12
# Use: Edit or de/comment (#) settings
# Latest modification: 2022.07.22
# Done: Update Nextclade to 2.3.0 from 1.11.0 conda env
###############################################################################

### CLUSTER ------------------------------------------------------------------------------------------
resources:
  cpus: 8           # Set maximum cpus usage (for multithreading, default: 8) [INT]
  mem_gb: 4         # Set maximum memory unsage (in Gb, default: 4) [INT]
  tmpdir: '$TMPDIR' # Temporary directory (default: '$TMPDIR')
  ## Examples:
    ## '$TMPDIR'  # System variable $TMPDIR (dafault)
    ## '.'        # Local (i.e. GeVarLi root directory)
    ## '/scratch' # HPC (set it to match your HPC usage)

### ENVIRONNEMENTS -----------------------------------------------------------------------------------
conda:                                            # Conda environement yaml files:
  bcftools:     '../envs/bcftools-1.15.1.yaml'     # Bcftools     ver. 1.15.1
  bedtools:     '../envs/bedtools-2.30.0.yaml'     # Bedtools     ver. 2.30.0
  bowtie2:      '../envs/bowtie2-2.4.5.yaml'       # Bowtie2      ver. 2.4.5
  bwa:          '../envs/bwa-0.7.17.yaml'          # BWA          ver. 0.7.17
  cutadapt:     '../envs/cutadapt-4.1.yaml'        # Cutadapt     ver. 4.1
  fastq-screen: '../envs/fastq-screen-0.15.2.yaml' # Fastq-Screen ver. 0.15.2
  fastqc:       '../envs/fastqc-0.11.9.yaml'       # FastQC       ver. 0.11.9
  gawk:         '../envs/gawk-5.1.0.yaml'          # Awk          ver. 5.1.0
  lofreq:       '../envs/lofreq-2.1.5.yaml'        # Lofreq       ver. 2.1.5
  multiqc:      '../envs/multiqc-1.12.yaml'        # MultiQC      ver. 1.12
  nextclade:    '../envs/nextclade-2.3.0.yaml'     # Nextclade    ver. 2.3.0
  pangolin:     '../envs/pangolin-4.0.6.yaml'      # Pangolon     ver. 4.0.6
  samtools:     '../envs/samtools-1.15.1.yaml'     # Samtools     ver. 1.15.1
  sickle-trim:  '../envs/sickle-trim-1.33.yaml'    # Sickle-trim  ver. 1.33

### ALIGNER ------------------------------------------------------------------------------------------
aligner: 'bwa' # Select your favorite aligner (default: 'bwa')
## Available options:
  ## 'bwa'     # Faster (default)
  ## 'bowtie2' # Slower, 'sensitivity' requiried and should be set (see below "Bowtie2" options)

### CONSENSUS ----------------------------------------------------------------------------------------
consensus:
  reference: 'SARS-CoV-2_Wuhan-WIV04_2019' # Your favorite reference, in fasta format
  ## Available options:
    ## 'SARS-CoV-2_Wuhan-WIV04_2019' # SARS-CoV-2_Wuhan_ NC_045512.2 (default)
    ## 'Monkeypox-virus_Zaire'       # Monkeypox_Zaire_NC_003310.1   (not working with Bowtie2, Nextclade and Pangolin)
    ## 'Ebola-virus_Zaire'           # Ebola_Zaire_NC_002549.1       (not working with Bowtie2, Nextclade and Pangolin)
    ## 'HIV-1_HXB2'                  # HIV-1_HXB2                    (not working with Bowtie2, Nextclade and Pangolin)
  genomes: 'resources/genomes/' # Path to your favorite reference 
  mincov: 3 # Minimum coverage, mask lower regions with 'N' (default: '10') [INT]
  minaf: 0.2 # Minimum allele frequency allowed (default: '0.2') [FLOAT]
  iupac: ''  # Output variants in the form of IUPAC ambiguity codes (default: deactivate)
  ## Available options:
    ## ''        # Deactivate
    ## '--iupac' # Activate

### GISAID -------------------------------------------------------------------------------------------
gisaid:
  threshold: '30'
  name: 'hCoV-19'
  country: 'France'
  #identifier: ''
  year: '2022'

### BWA ----------------------------------------------------------------------------------------------
bwa:
  indexes: 'resources/indexes/bwa/' # Path to BWA indexes

### BOWTIE2 ------------------------------------------------------------------------------------------
bowtie2:
  indexes: 'resources/indexes/bowtie2/' # Path to Bowtie2 indexes
  sensitivity: '--very-sensitive' # Bowtie2 sensitivity preset (default: '--very-sensitive')
  ## Available options:
    ## '--very-fast'      # Same as options: -D 5 -R 1 -N 0 -L 22 -i S,0,2.50
    ## '--fast'           # Same as options: -D 10 -R 2 -N 0 -L 22 -i S,0,2.50
    ## '--sensitive'      # Same as options: -D 15 -R 2 -N 0 -L 22 -i S,1,1.15
    ## '--very-sensitive' # Same as options: -D 20 -R 3 -N 0 -L 20 -i S,1,0.50 (default)

### NEXTCLADE ----------------------------------------------------------------------------------------
nextclade:
  dataset: 'resources/nextclade/sars-cov-2/' # Nextclade sars-cov-2 default dataset (for nextclade 1.10.1)

### SICKLE-TRIM --------------------------------------------------------------------------------------
sickle-trim:
  command: 'pe'      # Reading (default and should be 'pe' for paired-end sequences)
  encoding: 'sanger' # Quality encoding (dafault, and sould be 'sanger')
  ## Available options (only for information):
    ## 'sanger'   # CASAVA >= 1.8 for "recent" Illumina reads (default)
    ## 'illumina' # CASAVA 1.3 to 1.7 for "old" Illumina reads
    ## 'solexa'   # CASAVA < 1.3 for Solexa
  quality: '30'      # Phred score limit (default: '30')
  length: '50'       # Read length limit after trim (default: '50')

### CUTADAPT -----------------------------------------------------------------------------------------
cutadapt:
  length: '50' # Discard reads shorter than 'length' after trim (default: '50')
  kits:        # Sequence of an adapter ligated to the 3' end of the first read
    truseq:  'AGATCGGAAGAGC'         # Illumina "TruSeq" or "ScriptSeq" based libraries kits
    nextera: 'CTGTCTCTTATACACATC'    # Illumina "Nextera" or "TruSight" based libraries kits
    small:   'TGGAATTCTCGGGTGCCAAGG' # Illumina "Small" based libraries kits

### FASTQSCREEN --------------------------------------------------------------------------------------
fastq-screen:
  config: 'config/fastq-screen.conf' # Path to the fastq-screen configuration file
  subset: 1000                       # Don't use the whole sequence file, but sub-dataset of specified number of read (default: '1000') [INT] (0='all')
  aligner: 'bwa'                     # Aligner for fastq-screen (default and should be 'bwa')
  ## Available options:
    ## 'bwa'     # Burrows-Wheeler Aligner (default, somme small genomes indexes provided, see 'fastq-screen.conf')
    ## 'bowtie'  # Bowtie (indexes not provided)
    ## 'bowtie2' # Bowtie2 (indexes not provided)
