
###############################################################################
# Name: fastq-screen.conf
# Author: Nicolas Fernandez
# Affiliation: IRD_TransVIHMI
# Aim: Configuration file for Fastq-Screen (with bwa) for gevarli.smk snakefile
# Date: 2021.04.30
# Use: Edit or de/comment (#)
# Latest modification: 2022.06.16
# Todo: done
###############################################################################

#### MOLECULAR BIOLOGY SEQUENCES ----------------------------------------------------------------------------

### PhiX - sequence available from Refseq accession NC_001422.1
DATABASE	PhiX	      resources/indexes/bwa/Phi-X174
### Adapters - sequence derived from the FastQC contaminants (www.bioinformatics.babraham.ac.uk/projects/fastqc)
DATABASE	Adapters	resources/indexes/bwa/Adapters
### Vector - sequence taken from the UniVec database (http://www.ncbi.nlm.nih.gov/VecScreen/UniVec.html) BUT without phi-X174
DATABASE	Vectors	    resources/indexes/bwa/UniVec_wo_phi-X174

#### TRANSVIHMI ORGANISMS -----------------------------------------------------------------------------------

#### Putative Hosts  (Large genomes) -----

### Gorilla g4
#DATABASE	Gorilla	resources/indexes/bwa/Gorilla_gorilla_g4
### Chimpanzee t3
#DATABASE    Chimpanzee	resources/indexes/bwa/Pan_troglodytes_t3
### Human h38
DATABASE	Human	resources/indexes/bwa/Homo_sapiens_h38
### Bat v1
#DATABASE	Bat	resources/indexes/bwa/Pteropus_vampyrus_v1

#### Main Viruses (Small genomes) -----

### HIV-1_HXB2_K03455.1
DATABASE	HIV	resources/indexes/bwa/HIV-1_HXB2
### Ebola_Zaire_NC_002549.1
DATABASE	Ebola	resources/indexes/bwa/Ebola-virus_Zaire
### Monkeypox_Zaire_NC_003310.1
DATABASE	Monkeypox	resources/indexes/bwa/Monkeypox-virus_Zaire
### SARS-CoV-2_Wuhan_ NC_045512.2
DATABASE	SARS-CoV-2	resources/indexes/bwa/SARS-CoV-2_Wuhan-WIV04_2019

#### LAB MODEL ORGANISMS ------------------------------------------------------------------------------------

### E. coli (Bacteria) - sequence available from EMBL (accession U00096.2)
DATABASE	Ecoli  resources/indexes/bwa/Echerichia_coli_U00096
### S. cerevisiae (Yeast) - sequence
#DATABASE	  Scerevisiae	resources/indexes/bwa/Saccharomyces_cerevisiae
### C. elegans (Nematode) - sequence
#DATABASE	  Celegans	resources/indexes/bwa/Caenorhabditis_elegans
### D. melanogaster (Fruit fly) - sequence
#DATABASE	  Dmelanogaster	resources/indexes/bwa/Drosophila_melanogaster
### D. rerio (Zebrafish) - sequence
#DATABASE  Drerio      resources/indexes/bwa/Danio_rerio
### X. laevis (Xenope) - sequence
#DATABASE   Xlaevis  resources/indexes/bwa/Xenopus_laevis
### G. gallus - sequence
#DATABASE  Ggallus	ressources/indexes/bwa/Gallus_gallus
### Mouse m39
#DATABASE	Mouse	 resources/indexes/bwa/Mus_musculus_m39
### Arabidopsis t10 (Plant) - sequence from NCBI (ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.3_TAIR10/GCF_000001735.3_TAIR10_genomic.fna.gz)
#DATABASE	Arabidopsis	 resources/indexes/bwa/Arabidopsis_thaliana_t10
