###I###R###D######U###2###3###3#######T###R###A###N###S###V###I###H###M###I####
# Name ___________________ fastq-screen.conf
# Version ________________ v.2022.11
# Author _________________ Nicolas Fernandez
# Affiliation ____________ IRD_TransVIHMI
# Aim ____________________ Configuration file for Fastq-Screen (with bwa)
# Date ___________________ 2021.04.30
# Latest modifications ___ 2022.11.18
# Use ____________________ Edit default settings (and add fasta reference)

###############################################################################

#### MOLECULAR BIOLOGY SEQUENCES ----------------------------------------------------------------------------

### PhiX - QC_phi-X174_Coliphage_NC-001422.1
DATABASE	PhiX		resources/indexes/bwa/Phi-X174_Coliphage_NC-001422-1
### Kanamycin - QC_Kanamycin-Resistance-Gene
DATABASE      	Kanamycin	resources/indexes/bwa/Kanamycin-Resistance-Gene
### Adapters - QC_NGS-Adapters (FastQC contaminants: www.bioinformatics.babraham.ac.uk/projects/fastqc)
DATABASE	Adapters	resources/indexes/bwa/NGS-adapters
### Vectors - QC_UniVec_wo_PhiX_and_Kanamycin (UniVec database: http://www.ncbi.nlm.nih.gov/VecScreen/UniVec.html) without PhiX and Kanamycin
DATABASE	Vectors		resources/indexes/bwa/UniVec_wo_phiX_and_kanamycin

#### TRANSVIHMI ORGANISMS -----------------------------------------------------------------------------------

#### Putative Hosts  (Large genomes) -----

### Gorilla g4
#DATABASE	Gorilla		resources/indexes/bwa/Gorilla-gorilla_g4
### Chimpanzee t3
#DATABASE	Chimpanzee	resources/indexes/bwa/Pan_troglodytes_t3
### Human - Homo-sapiens_h38_NC-000001.11
#DATABASE	Human		resources/indexes/bwa/Homo-sapiens_h38_NC000001-11
### Bat v1
#DATABASE	Bat		resources/indexes/bwa/Pteropus-vampyrus_v1

#### Main Viruses (Small genomes) -----

### SARS-CoV-2 - SARS-CoV-2_Wuhan_MN908947.3
DATABASE	SARS-CoV-2	resources/indexes/bwa/SARS-CoV-2_Wuhan_MN908947-3
### MPXV - Monkeypox-virus_Zaire_AF380138.1
DATABASE	Monkeypox	resources/indexes/bwa/Monkeypox-virus_Zaire_AF380138-1
### SPXV - Swinepox-virus_India_MW036632.1
DATABASE	Swinepox	resources/indexes/bwa/Swinepox-virus_India_MW036632-1
### EBOV - Ebola-virus_Zaire_AF272001.1
DATABASE	Ebola		resources/indexes/bwa/Ebola-virus_Zaire_AF272001-1
### HIV - HIV-1_HXB2_K03455.1
DATABASE	HIV		resources/indexes/bwa/HIV-1_HXB2_K03455-1

#### LAB MODEL ORGANISMS ------------------------------------------------------------------------------------

### E. coli (Bacteria) - QC_Echerichia-coli_CP060121.1
DATABASE	Ecoli		resources/indexes/bwa/Echerichia-coli_CP060121-1
### S. cerevisiae (Yeast) - sequence
#DATABASE	Scerevisiae	resources/indexes/bwa/Saccharomyces-cerevisiae
### C. elegans (Nematode) - sequence
#DATABASE	Celegans	resources/indexes/bwa/Caenorhabditis-elegans
### D. melanogaster (Fruit fly) - sequence
#DATABASE	Dmelanogaster	resources/indexes/bwa/Drosophila-melanogaster
### D. rerio (Zebrafish) - sequence
#DATABASE    	Drerio		resources/indexes/bwa/Danio-rerio
### X. laevis (Xenope) - sequence
#DATABASE     	Xlaevis		resources/indexes/bwa/Xenopus-laevis
### G. gallus - sequence
#DATABASE     	Ggallus		ressources/indexes/bwa/Gallus-gallus
### Mouse m39
#DATABASE	Mouse		resources/indexes/bwa/Mus-musculus_m39
### Arabidopsis t10 (Plant) - sequence from NCBI (ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.3_TAIR10/GCF_000001735.3_TAIR10_genomic.fna.gz)
#DATABASE	Arabidopsis	resources/indexes/bwa/Arabidopsis-thaliana_t10_NC003070-9
