
###############################################################################                                                                                                                                  
# Author: Nicolas Fernandez
# Affiliation: IRD_TransVIHMI
# Aim: Config file for Fastq-Screen, with bwa, for GeVarLi pipeline
# Date: 2021.04.30
# Use: Edit, (de)comment settingss you want modify
# Latest modification: 2021.01.03
# Todo: na
###############################################################################                                                                                                                                  

## MOLECULAR BIOLOGY SEQUENCES -----------------------------------------------------------------------
# PhiX - sequence available from Refseq accession NC_001422.1
DATABASE	PhiX	 resources/databases/bwa/Phi-X174
# Adapters - sequence derived from the FastQC contaminants (www.bioinformatics.babraham.ac.uk/projects/fastqc)
DATABASE	Adapters        resources/databases/bwa/Adapters
# Vector - sequence taken from the UniVec database (http://www.ncbi.nlm.nih.gov/VecScreen/UniVec.html) BUT without phi-X174
DATABASE	Vectors		 resources/databases/bwa/UniVec_wo_phi-X174

## LAB ORGANISMS -------------------------------------------------------------------------------------
# Smallest -----
# HIV - HXB2
DATABASE	HIV	 resources/databases/bwa/HIV_HXB2
# Ebola - sequence available from NCBI (accession NC_002549)
DATABASE	Ebola	 resources/databases/bwa/Ebola_ZEBOV
# SARS-CoV-2 - sequence from Whuhan available from NCBI (accession NC_045512.2)
DATABASE	SARS-CoV-2	 resources/databases/bwa/SARS-CoV-2_Wuhan-WIV04_2019

# Larger -----
# Gorilla g4	
#DATABASE	Gorilla	 resources/databases/bwa/Gorilla_gorilla_g4
# Chimpanzee t3
#DATABASE	Chimpanzee	 resources/databases/bwa/Pan_troglodytes_t3
# Bat v1
#DATABASE	Bat	 resources/databases/bwa/Pteropus_vampyrus_v1

## MODEL ORGANISMS -----------------------------------------------------------------------------------
# Human h38
#DATABASE	Human	 resources/databases/bwa/Homo_sapiens_h38
# Mouse m39
#DATABASE	Mouse	 resources/databases/bwa/Mus_musculus_m39
# Arabidopsis t10 - sequence from NCBI (ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/001/735/GCF_000001735.3_TAIR10/GCF_000001735.3_TAIR10_genomic.fna.gz)
#DATABASE	Arabidopsis	 resources/databases/bwa/Arabidopsis_thaliana_t10
# Ecoli - sequence available from EMBL (accession U00096.2)
DATABASE	Ecoli	 resources/databases/bwa/Echerichia_coli_U00096
