$schema: "http://json-schema.org/draft-07/schema#"
title: "GeVarLi Config Schema"
type: object
properties:
  fastq_dir:
    type: string
  modules:
    type: object
    properties:
      qualities:
        type: boolean
      keeptrim:
        type: boolean
      clipping:
        type: boolean
      covstats:
        type: boolean
      consensus:
        type: boolean
      lineages:
        type: boolean
      gisaid:
        type: boolean
    required:
      - qualities
      - keeptrim
      - clipping
      - covstats
      - consensus
      - lineages
      - gisaid
  tools:
    type: object
    properties:
      mapper:
        type: string
      caller:
        type: string
      assigner:
        type: string
    required:
      - mapper
      - caller
      - assigner
  consensus:
    type: object
    properties:
      reference:
        type: string
    required:
      - reference
  gisaid:
    type: object
    properties:
      username:
        type: string
      threshold:
        type: string
      name:
        type: string
      country:
        type: string
      identifier:
        type: string
      year:
        type: string
    required:
      - username
      - threshold
      - name
      - country
      - identifier
      - year
  nextclade:
    type: object
    properties:
      path:
        type: string
      dataset:
        type: string
    required:
      - path
      - dataset
  ivar:
    type: object
    properties:
      consensus:
        type: object
        properties:
          min_depth:
            type: string
          max_depth:
            type: string
          min_freq:
            type: string
          map_qual:
            type: string
          min_bq:
            type: string
          min_qual:
            type: string
        required:
          - min_depth
          - max_depth
          - min_freq
          - map_qual
          - min_bq
          - min_qual
      variant:
        type: object
        properties:
          min_depth:
            type: string
          max_depth:
            type: string
          min_freq:
            type: string
          map_qual:
            type: string
          min_bq:
            type: string
          min_qual:
            type: string
        required:
          - min_depth
          - max_depth
          - min_freq
          - map_qual
          - min_bq
          - min_qual
      primerclipping:
        type: [ "object", "null" ]
    required:
      - consensus
      - variant
      - primerclipping
  bamclipper:
    type: object
    properties:
      path:
        type: string
      primers:
        type: string
      upstream:
        type: string
      downstream:
        type: string
    required:
      - path
      - primers
      - upstream
      - downstream
  bwa:
    type: object
    properties:
      algorithm:
        type: string
    required:
      - algorithm
  bowtie2:
    type: object
    properties:
      algorithm:
        type: string
      sensitivity:
        type: string
    required:
      - algorithm
      - sensitivity
  minimap2:
    type: object
    properties:
      algorithm:
        type: object
        properties:
          k-mer_size:
            type: string
          minimizer_size:
            type: string
          split_size:
            type: string
          homopolymer:
            type: string
        required:
          - k-mer_size
          - minimizer_size
          - split_size
          - homopolymer
      preset:
        type: string
    required:
      - algorithm
      - preset
  sickle_trim:
    type: object
    properties:
      quality:
        type: string
      length:
        type: string
      command:
        type: string
      encoding:
        type: string
    required:
      - quality
      - length
      - command
      - encoding
  cutadapt:
    type: object
    properties:
      clipping:
        type: string
      length:
        type: string
      kits:
        type: object
        properties:
          truseq:
            type: string
          nextera:
            type: string
          small:
            type: string
        required:
          - truseq
          - nextera
          - small
    required:
      - clipping
      - length
      - kits
  multiqc:
    type: object
    properties:
      path:
        type: string
      config:
        type: string
      tag:
        type: string
    required:
      - path
      - config
      - tag
  fastq_screen:
    type: object
    properties:
      config:
        type: string
      subset:
        type: string
      reference:
        type: array
        items:
          type: string
    required:
      - config
      - subset
      - reference
  rename:
    type: object
    properties:
      barcode_id:
        type: boolean
      line_id:
        type: boolean
      end_id:
        type: boolean
    required:
      - barcode_id
      - line_id
      - end_id
  resources:
    type: object
    properties:
      cpus:
        type: string
      ram:
        type: string
      tmp_dir:
        type: string
    required:
      - cpus
      - ram
      - tmp_dir
  envs:
    type: object
    properties:
      bamclipper:
        type: string
      bcftools:
        type: string
      bedtools:
        type: string
      bowtie2:
        type: string
      bwa:
        type: string
      cutadapt:
        type: string
      fastq_screen:
        type: string
      fastqc:
        type: string
      gawk:
        type: string
      ivar:
        type: string
      minimap2:
        type: string
      multiqc:
        type: string
      nextclade:
        type: string
      pangolin:
        type: string
      samtools:
        type: string
      sickle_trim:
        type: string
      tsv2vcf:
        type: string
      workflow:
        type: string
    required:
      - bamclipper
      - bcftools
      - bedtools
      - bowtie2
      - bwa
      - cutadapt
      - fastq_screen
      - fastqc
      - gawk
      - ivar
      - minimap2
      - multiqc
      - nextclade
      - pangolin
      - samtools
      - sickle_trim
      - tsv2vcf
      - workflow
  report:
    type: object
    properties:
      stat:
        type: object
        properties:
          extention:
            type: array
            items:
              type: string
        required:
          - extention
      graph:
        type: object
        properties:
          type:
            type: array
            items:
              type: string
          extention:
            type: array
            items:
              type: string
        required:
          - type
          - extention
    required:
      - stat
      - graph
required:
  - fastq_dir
  - modules
  - tools
  - consensus
  - gisaid
  - nextclade
  - ivar
  - bamclipper
  - bwa
  - bowtie2
  - minimap2
  - sickle_trim
  - cutadapt
  - multiqc
  - fastq_screen
  - rename
  - resources
  - envs
  - report